Traceback (most recent call last):
  File "C:\Users\ee303\hanaa\test\hyper.py", line 141, in <module>
    model.fit()
  File "C:\Users\ee303\anaconda3\envs\recommenders\lib\site-packages\recommenders\models\deeprec\models\graphrec\lightgcn.py", line 272, in fit
    for metric, r in zip(self.metrics, ret)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\ee303\hanaa\test\hyper.py", line 141, in <module>
    model.fit()
  File "C:\Users\ee303\anaconda3\envs\recommenders\lib\site-packages\recommenders\models\deeprec\models\graphrec\lightgcn.py", line 272, in fit
    for metric, r in zip(self.metrics, ret)
TypeError: 'NoneType' object is not iterable